export const Post = () => {
  return (
    <>
      <div className="relative mt-20 mx-10 max-w-container px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col">
          <h1 className="mt-3 text-5xl font-bold tracking-tight text-slate-900">
            Title
          </h1>
          <h2 className="mt-1 text-s leading-6 text-gray-400">
            User posted at 27/06/2001 16:00
          </h2>
          <p className="mt-10 text-xl leading-6 text-gray-600">
            This is a generic post generated by a generic human doing generic
            stuff. Because we like the breathe air.
          </p>

          <div className="space-y-12">
            <div className="border-b border-gray-900/10 pb-12"></div>
          </div>

          <h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-900">
            Comments
          </h1>

          <div className="my-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
            <div className="col-span-full">
              <textarea
                id="comment"
                name="comment"
                className="block w-full rounded-md border-0 py-1.5 text-xl text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                defaultValue={""}
              />
            </div>
            <input
              type="submit"
              value="Comment"
              className="flex w-40 rounded-md bg-indigo-600 py-1.5 text-l font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
            />
          </div>
        </div>

        <h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-900">
          Comment
        </h1>
        <h2 className="mt-1 text-s leading-6 text-gray-400">
          User posted at 27/06/2001 16:00
        </h2>
        <p className="mt-10 text-xl leading-6 text-gray-600">
          This is a comment
        </p>

        <div className="space-y-12">
          <div className="border-b border-gray-900/10 pb-12"></div>
        </div>
      </div>
    </>
  );
};
